/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
"use strict";function showPartsSplash(t){perf.mark("willShowPartsSplash"),perf.mark("willAccessLocalStorage");let e=window.localStorage;perf.mark("didAccessLocalStorage");let o;try{let t=e.getItem("storage://global/parts-splash-data");o=JSON.parse(t)}catch(t){}o&&t.highContrast&&"hc-black"!==o.baseTheme&&(o=void 0),o&&t.extensionDevelopmentPath&&(o.layoutInfo=void 0);const i=o?o.baseTheme:t.highContrast?"hc-black":"vs-dark",r=o?o.colorInfo.editorBackground:t.highContrast?"#000000":"#1E1E1E",a=o?o.colorInfo.foreground:t.highContrast?"#FFFFFF":"#CCCCCC",n=document.createElement("style");if(n.className="initialShellColors",document.head.appendChild(n),document.body.className=`monaco-shell ${i}`,n.innerHTML=`.monaco-shell { background-color: ${r}; color: ${a}; }`,o&&o.layoutInfo){const{id:e,layoutInfo:i,colorInfo:r}=o,a=document.createElement("div");a.id=e,i.sideBarWidth=Math.min(i.sideBarWidth,window.innerWidth-(i.activityBarWidth+i.editorPartMinWidth)),
t.folderUri||t.workspace?a.innerHTML=`\n\t\t\t<div style="position: absolute; width: 100%; left: 0; top: 0; height: ${i.titleBarHeight}px; background-color: ${r.titleBarBackground}; -webkit-app-region: drag;"></div>\n\t\t\t<div style="position: absolute; height: calc(100% - ${i.titleBarHeight}px); top: ${i.titleBarHeight}px; ${i.sideBarSide}: 0; width: ${i.activityBarWidth}px; background-color: ${r.activityBarBackground};"></div>\n\t\t\t<div style="position: absolute; height: calc(100% - ${i.titleBarHeight}px); top: ${i.titleBarHeight}px; ${i.sideBarSide}: ${i.activityBarWidth}px; width: ${i.sideBarWidth}px; background-color: ${r.sideBarBackground};"></div>\n\t\t\t<div style="position: absolute; width: 100%; bottom: 0; left: 0; height: ${i.statusBarHeight}px; background-color: ${r.statusBarBackground};"></div>\n\t\t\t`:a.innerHTML=`\n\t\t\t<div style="position: absolute; width: 100%; left: 0; top: 0; height: ${i.titleBarHeight}px; background-color: ${r.titleBarBackground}; -webkit-app-region: drag;"></div>\n\t\t\t<div style="position: absolute; height: calc(100% - ${i.titleBarHeight}px); top: ${i.titleBarHeight}px; ${i.sideBarSide}: 0; width: ${i.activityBarWidth}px; background-color: ${r.activityBarBackground};"></div>\n\t\t\t<div style="position: absolute; width: 100%; bottom: 0; left: 0; height: ${i.statusBarHeight}px; background-color: ${r.statusBarNoFolderBackground};"></div>\n\t\t\t`,
document.body.appendChild(a)}perf.mark("didShowPartsSplash")}function getLazyEnv(){const t=require("electron").ipcRenderer;return new Promise(function(e){const o=setTimeout(function(){e(),console.warn("renderer did not receive lazyEnv in time")},1e4);t.once("vscode:acceptShellEnv",function(t,i){clearTimeout(o),bootstrapWindow.assign(process.env,i),e(process.env)}),t.send("vscode:fetchShellEnv")})}const perf=require("../../../base/common/performance");perf.mark("renderer/started");const bootstrapWindow=require("../../../../bootstrap-window");process.lazyEnv=getLazyEnv(),bootstrapWindow.load(["vs/workbench/workbench.main","vs/nls!vs/workbench/workbench.main","vs/css!vs/workbench/workbench.main"],function(t,e){return perf.mark("didLoadWorkbenchMain"),process.lazyEnv.then(function(){return perf.mark("main/startup"),require("vs/workbench/electron-browser/main").startup(e)})},{removeDeveloperKeybindingsAfterLoad:!0,canModifyDOM:function(t){showPartsSplash(t)},beforeLoaderConfig:function(t,e){
const o=window.MonacoEnvironment.onNodeCachedData=[];e.onNodeCachedData=function(){o.push(arguments)},e.recordStats=!!t.performance},beforeRequire:function(){perf.mark("willLoadWorkbenchMain")}});
//# sourceMappingURL=https://ticino.blob.core.windows.net/sourcemaps/3368db6750222d319c851f6d90eb619d886e08f5/core/vs/code/electron-browser/workbench/workbench.js.map
